paths:
  contracts: contracts/
  artifacts: .gltest_cache/
networks:
  default: localnet
  localnet:
    url: http://127.0.0.1:4000/api
    leader_only: true
    chain_type: localnet
  testnet-bradbury:
    url: https://rpc-bradbury.genlayer.com/api
    chain_type: testnet_asimov
    accounts:
    - '0xc7493f3dcee304b55b0a7284642a929bf8f1455026557e99517c7575861fd073'
    id: 4221
